### ISSUE TITLE
Unable to run web server

### ISSUE THREAD

**Issue by mrcrocodile556** [alext-mkrs/edison-mon-sys#3]
Hello, 
I am able to run my webpage unfortunately with a blank webpage.

For Step 3,
I have created a user, home directory and a group.
Copied init.d into my /etc directory.
Copied "scripts" from your repo to /home/motion directory.
- changed the IP address in index.html
- did a npm install in script however i got a warning of 
  `npm WARN package.json motion-edison-demo-webserver@0.1.0 No repository field.`

Did i do something wrongly here? 
Can you guide me on what are the necessary node.js modules for web server?

**Comment by alext-mkrs** [comment]
I'll have more details in the evening today, but generally, the requirement is only Express framework, npm should have installed it for you (it's listed in package.json).

Are you able to connect to Motion stream directly (port is specified in motion.conf)?

**Comment by alext-mkrs** [comment]
In addition to the above - it's not stated explicitly in the readme, but you have to start the server after installing necessary modules via npm. You do this by 'node server.js'. Did you do this? If the server is started, you to at least get the web page with static text even if Motion is not started.

**Comment by mrcrocodile556** [comment]
Thank you, however there is a problem with my motion.

After running the command of `motion`

This is the output i receive,

```
[0] Processing thread 0 - config file /etc/motion.conf
[0] Unknown config option "ffmpeg_cap_new"
[0] Unknown config option "ffmpeg_cap_motion"
[0] Unknown config option "ffmpeg_timelapse"
[0] Unknown config option "ffmpeg_timelapse_mode"
[0] Unknown config option "ffmpeg_bps"
[0] Unknown config option "ffmpeg_variable_bitrate"
[0] Unknown config option "ffmpeg_video_codec"
[0] Unknown config option "ffmpeg_deinterlace"
[0] Unknown config option "movie_filename"
[0] Unknown config option "timelapse_filename"
[0] Motion 8.4.0 Started
[0] Thread 1 is from /etc/motion.conf
[0] motion-httpd/8.4.0 running, accepting connections
[0] motion-httpd: waiting for data on port TCP 8080
[1] Thread 1 started
[1] config image height (120) is not modulo 16
[1] Could not fetch initial image from camera
[1] Motion continues using width and height from config file(s)
[1] Resizing pre_capture buffer to 1 items
[1] Started stream webcam server in port 8081
[1] Resizing pre_capture buffer to 3 items
[1] Retrying until successful connection with camera
[1] config image height (120) is not modulo 16
[1] Retrying until successful connection with camera
[1] config image height (120) is not modulo 16
```

What does it mean by 
`[1] config image height (120) is not modulo 16`

I'm running on a small resolution size of 160 x 120.
Any idea what went wrong?

**Comment by alext-mkrs** [comment]
This sounds like an incorrect motion.conf to me. Try the one from this repo,without any modifications first.

I think the main error there is motion's inability to fetch the image from camera, check your driver and that the camera supports MJPEG format.

**Comment by mrcrocodile556** [comment]
I stick to the default motion.conf file from your repo at first and it gave me this error 

```
[0] Processing thread 0 - config file /etc/motion.conf
[0] Unknown config option "ffmpeg_cap_new"
[0] Unknown config option "ffmpeg_cap_motion"
[0] Unknown config option "ffmpeg_timelapse"
[0] Unknown config option "ffmpeg_timelapse_mode"
[0] Unknown config option "ffmpeg_bps"
[0] Unknown config option "ffmpeg_variable_bitrate"
[0] Unknown config option "ffmpeg_video_codec"
[0] Unknown config option "ffmpeg_deinterlace"
[0] Unknown config option "movie_filename"
[0] Unknown config option "timelapse_filename"
[0] Motion 8.4.0 Started
[0] Thread 1 is from /etc/motion.conf
[0] motion-httpd/8.4.0 running, accepting connections
[1] Thread 1 started
[0] motion-httpd: waiting for data on port TCP 8080
[1] cap.driver: "uvcvideo"
[1] cap.card: "UVC Camera (046d:0825)"
[1] cap.bus_info: "usb-dwc3-host.2-1"
[1] cap.capabilities=0x84000001
[1] - VIDEO_CAPTURE
[1] - STREAMING
[1] Test palette MJPG (640x480)
[1] Using palette MJPG (640x480) bytesperlines 0 sizeimage 341333 colorspace 00000008
[1] found control 0x00980900, "Brightness", range 0,255
[1]     "Brightness", default 128, current 128
[1] found control 0x00980901, "Contrast", range 0,255
[1]     "Contrast", default 32, current 32
[1] found control 0x00980902, "Saturation", range 0,255
[1]     "Saturation", default 32, current 32
[1] found control 0x00980913, "Gain", range 0,255
[1]     "Gain", default 64, current 64
[1] mmap information:
[1] frames=4
[1] 0 length=341333
[1] 1 length=341333
[1] 2 length=341333
[1] 3 length=341333
[1] Using V4L2
[1] Resizing pre_capture buffer to 1 items
Corrupt JPEG data: 1 extraneous bytes before marker 0xd1
Corrupt JPEG data: 5 extraneous bytes before marker 0xd7
Corrupt JPEG data: 1 extraneous bytes before marker 0xd2
Corrupt JPEG data: 1 extraneous bytes before marker 0xd5
Corrupt JPEG data: 3 extraneous bytes before marker 0xd0
[1] Error capturing first image
[1] Started stream webcam server in port 8081
[1] Resizing pre_capture buffer to 3 items
Corrupt JPEG data: 1 extraneous bytes before marker 0xd1
Corrupt JPEG data: 1 extraneous bytes before marker 0xd0
Corrupt JPEG data: 1 extraneous bytes before marker 0xd5
Corrupt JPEG data: 1 extraneous bytes before marker 0xd2
```

It is a continuous script that runs unless i Ctrl+C which outputs this error eventually

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'temboo/core/temboosession'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/motion/scripts/xively_post.js:37:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
[0] httpd - Finishing
[0] httpd Closing
[0] httpd thread exit
[0] Motion terminating

```

After doing some research i found out that there is extraneous bytes in the image therefore i tried reducing the resolution which gave me the error stated in the previous post.

I'm not sure what went wrong..

**Comment by alext-mkrs** [comment]
Okay, that sounds like a camera problem then-maybe its mjpeg support is broken. Or broken at that exact resolution. I'd suggest reading up about your cam, its uvcvideo driver compatibility and mjpeg support quality.

**Comment by mrcrocodile556** [comment]
I edited the following parameters and managed to run my motion without errors:
daemon on
stream_localhost off
webcontrol_localhost off
Am i getting the correct output after entering the command `motion` ?

```
[0] Processing thread 0 - config file /etc/motion.conf
[0] Unknown config option "ffmpeg_cap_new"
[0] Unknown config option "ffmpeg_cap_motion"
[0] Unknown config option "ffmpeg_timelapse"
[0] Unknown config option "ffmpeg_timelapse_mode"
[0] Unknown config option "ffmpeg_bps"
[0] Unknown config option "ffmpeg_variable_bitrate"
[0] Unknown config option "ffmpeg_video_codec"
[0] Unknown config option "ffmpeg_deinterlace"
[0] Unknown config option "movie_filename"
[0] Unknown config option "timelapse_filename"
[0] Motion 8.4.0 Started
[0] Motion going to daemon mode
```

However i can't seem to run my server now. 

After creating the groups, copying the scripts and editing index.html,
I run a `node server.js`in the /home/motion/scripts directory and went into my web server however nothing is being displayed.

Any idea what did i do wrong this time?
Is there any specific parameters i need to change?

**Comment by alext-mkrs** [comment]
Well, these options have in general nothing to do with errors you had in your logs before. both `_localhost` ones simply allow Motion to bind to addresses other than 127.0.0.1 (i.e. Motion's stream will be available for clients connecting from other hosts) and the `daemon` one is for having it run in the background - just like it says in the log file.

I think the errors are actually there, just not visible due to the `daemon` mode.

So let's split two things
1. server: to check this one, just run `node server.js` after running `npm install` in the respective dir - per readme instructions. After that you should see at least an empty page with "Webcam stream" text in it. If you don't - check that the web server is running by e.g. running `netstat` on the board and checking that `node` process is bound to the respective IP and port. If you need my help - console outputs or maybe screenshots would help.
2. Motion not being able to capture the stream from your webcam: the recommendation on this stays the same - just check that your webcam is actually supported by Edison's version of the uvcvideo driver (version is tied to the OS kernel version, which is 3.10 for Edison SW Release 2.1)

**Comment by alext-mkrs** [comment]
Is this still actual?

**Comment by alext-mkrs** [comment]
Closing for no response and a solution provided
